### ISSUE TITLE
Error when fetching empty table

### ISSUE THREAD

**Issue by gsidsid** [Danilo-Zekovic/react-tableql#48]
**Describe the bug**
I get the following errors when attempting to load the ApolloTableQL component with a query that yields no results: "TypeError: Cannot read property 'slice' of undefined"

Accompanied by "Uncaught (in promise) TypeError: Cannot read property 'slice' of undefined"

**Expected behavior**
Well, it should probably just render the table with no rows of data.

**Cause**
I suspect the cause is at the following lines of code. This seems resolvable with a simple check for undefined/emptiness.
https://github.com/Danilo-Zekovic/react-tableql/blob/master/src/TableQL/TableQL.tsx#L192-L194

**Desktop (please complete the following information):**
 - chrome

**Additional context**
I'd make a PR but not fantastic at React

**Comment by Danilo-Zekovic** [comment]
Sorry for the late update. I looked into it and made a fix. If you install beta version `0.1.0-beta.2` it should fix the issue you had. Please let me know if this fixed the problem.

**Comment by gsidsid** [comment]
Thanks! This fix has worked for us.
