### ISSUE TITLE
document is not defined error with nextjs

### ISSUE THREAD

**Issue by s-kris** [Danilo-Zekovic/react-tableql#50]
**Describe the bug**
Using ApolloTableQL wth nextjs results in 
`Server Error: document is not defined`

**To Reproduce**

1. create default nextjs app with npx create-next-app
2. add react-tableql to the app and implement any ApolloTableQL table 
3. npm run dev

**Expected behavior**
Table should display data

**Desktop:**
 - OS: OS X 10.15
 - Browser Chrome
 - Version 81

**Comment by Danilo-Zekovic** [comment]
Thank you for reporting the issue. Which version of react-tableql are you using, `0.0.10` or one of beta versions `0.1.0-beta.2`?

**Comment by s-kris** [comment]
I tested with both versions now. Sorry to miss out this detail. It is an ssr issue. `document` isn't available on server-side. 
The above error is caused when we reload the page or directly loading that page url.
It works fine with client-side navigation.

**Comment by Danilo-Zekovic** [comment]
Sorry, it took so long. Currently, react-tableql does not support the SSR out of the box. However, you are still able to use it with next.js. So to use it in next.js you will need to dynamically import it with SSR set to false as demonstrated in the example app that I recently created. Check the commit that demonstrates the solution that can help you:
 https://github.com/Danilo-Zekovic/react-tableql-nextjs-example-app/commit/b96904b41b7ca94762208dbd930f5c04260ecd02

Please let me know did this help solve your problem?

**Comment by s-kris** [comment]
Thank you Danilo, not a problem. Yes, it works with dynamic import.
Sorry I had to use material-table with my own implementation for custom requirements.
